language: rust

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"

rust:
  - stable
  - nightly

matrix:
  fast_finish: true

cache: cargo

before_script:
  - pip3 install --user travis-wait-improved

script:
  - python3 ~/.local/bin/travis-wait-improved --timeout=30m 'cargo test --all -- --skip "dpc" --skip "integration_test"'
  - python3 ~/.local/bin/travis-wait-improved --timeout=30m 'cargo check --examples --all'
